# Generated by Django 5.2 on 2025-06-12 18:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileToEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.BigIntegerField(unique=True, verbose_name='ID ТГ-профиля')),
                ('username', models.CharField(verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('location', models.CharField(verbose_name='Место')),
                ('datetime', models.DateTimeField(verbose_name='Время')),
                ('participants_requirements', models.CharField(verbose_name='Требования к участникам')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество мест')),
                ('cover', models.ImageField(upload_to='app/covers/', verbose_name='Обложка')),
                ('profile', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.profiletoevents')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
