# Generated by Django 5.2 on 2025-06-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.TextField(blank=True, verbose_name='Участники'),
        ),
    ]
