# Generated by Django 5.2 on 2025-06-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants_requirements',
            field=models.CharField(max_length=255, verbose_name='Требования к участникам'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
