# Generated by Django 5.2 on 2025-06-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletoevents',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Username'),
        ),
    ]
